# Gradle
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=com.mclegoman
user=mclegoman
slug=loafy
modId=loafy
modName=Loafy
modDescription=All items now look like BREAD.
authors=dannytaylor
contributors=
license=LGPL-3.0-or-later
# Mod Version
modVersion=1.2.0
# Branch Metadata
branchName=fabric-1.21.8
compatibleVersions=1.21.8
compatibleLoaders=fabric, quilt
